### ISSUE TITLE
Look into state level under-reporting factors

### ISSUE THREAD

**Issue by JoviaNierenberg** [JoviaNierenberg/COVID-Event-Safety-Modeling#100]
Possibly based on mortality and age. Alyssa sent a [paper](https://www.sciencedirect.com/science/article/pii/S253104372030129X) that used mortality data early in the pandemic for this.

**Comment by adm2583** [comment]
I think it is that article, the only other one I've found so far is earlier in the pandemic and mentions a three approaches.

**Comment by adm2583** [comment]
After reading it though, I'm not sure that we could scale it by his paper without extensive coding. From my understanding of his paper, he took datasets from each state and different times before and after COVID-19 and looked for "influenza like illnesses."
