### ISSUE TITLE
Antigen testing - discuss using Ct values briefly in discussion

### ISSUE THREAD

**Issue by JoviaNierenberg** [JoviaNierenberg/COVID-Event-Safety-Modeling#104]
There are critiques of using Ct values that we should mention, pertaining to non-linearlity of viral load and infectiousness. See if they're mentioned in the [review of antigen tests](https://www.cochranelibrary.com/cdsr/doi/10.1002/14651858.CD013705.pub2/full) that we already cite. Otherwise find another paper to cite on the topic.

**Comment by adm2583** [comment]
Article mentioning the sensitivity of Binax rapid antigen test, they also discuss CT values and the roles that those play. Downside is they don't actually mention a percent sensitivity, just equates it to that of RT-PCR. Title: Analytical Sensitivity of the Abbott BinaxNOW COVID-19 Ag Card
link: https://www-ncbi-nlm-nih-gov.srv-proxy1.library.tamu.edu/pmc/articles/PMC8106729/
However, this preprint does give a sensitivity for the Binax test (93.3%). Title: Performance characteristics of a rapid SARS-CoV-2 antigen detection assay at a public plaza testing site in San Francisco
link: https://www-ncbi-nlm-nih-gov.srv-proxy1.library.tamu.edu/pmc/articles/PMC7654907/
