### ISSUE TITLE
Hypothesis

### ISSUE THREAD

**Issue by JoviaNierenberg** [JoviaNierenberg/COVID-Event-Safety-Modeling#12]
This is certainly a falsifiable hypothesis, but the answer is also a bit obvious; of course vaccination and testing can be used with NPIs to prevent morbidity and mortality! Can we sharpen this up to discuss their relative importance in different contexts, potentially? When might vaccination beat out all other options? When might we need to use testing or NPIs instead? How do the latter options compare to the former? What do the combinatorics suggest?

**Comment by jonahdf** [comment]
Will adjust as we find more combinations that aren't intuitive or obvious.
https://github.com/jonahdf/COVID-Event-Safety-Modeling/issues/7

**Comment by JoviaNierenberg** [comment]
Look at COVASIM paper for ideas

**Comment by JoviaNierenberg** [comment]
Changed to "This project aims to test the safety of holding events based on event size and user-specified mitigation measures, based on previously published estimates of COVID prevalence and population susceptibility, to produce guidance on whether events can be held safely. While vaccination, testing, and NPI use all reduce risk, they do not remove it entirely. We believe that visual representations of risk based on the available data and evidence will facilitate decision making for event planners. "
