### ISSUE TITLE
Assumptions - Methods

### ISSUE THREAD

**Issue by JoviaNierenberg** [JoviaNierenberg/COVID-Event-Safety-Modeling#14]
There are lots of assumptions here, which is OK -- but every assumption needs a citation and an explanation to demonstrate precedent as well as logic

**Comment by jonahdf** [comment]
Prevalence of B.1.1.7 is a big one

**Comment by JoviaNierenberg** [comment]
Read through the paper and comment on any assumptions that don't make sense or need more work

**Comment by s67sea** [comment]
https://docs.google.com/document/d/18vm3BvP2tFwlX8lqerXjSYHFhKMP3iQxV79R_YXqwmw/edit

**Comment by JoviaNierenberg** [comment]
Assumptions all have citations
