### ISSUE TITLE
Variants 

### ISSUE THREAD

**Issue by JoviaNierenberg** [JoviaNierenberg/COVID-Event-Safety-Modeling#19]
B117 isn't the only VOC circulating in the US right now; would mention P1 and B1351 too

**Comment by JoviaNierenberg** [comment]
This was commented on both times B117 was mentioned

**Comment by jonahdf** [comment]
https://outbreak.info/ is a good source for tracking variants

**Comment by JoviaNierenberg** [comment]
Say more transmissible variants

**Comment by adm2583** [comment]
In the past 60 days as of June 23, 2021 - variant prevalence in the U.S.: 
67% B.117
12% B.1526
9% P1
3% B16172
9% other
These numbers came from https://outbreak.info/

**Comment by adm2583** [comment]
Look up the synonyms for the variant numbers. 
Which naming system should we use for the variants?

**Comment by adm2583** [comment]
B117 = alpha
B1526  = iota
P1 = gamma
B16172 = delta 

Alpha, beta, delta, and gamma are considered variants of concern in the U.S. by the CDC.
Source: https://www.cdc.gov/coronavirus/2019-ncov/variants/variant-info.html

**Comment by JoviaNierenberg** [comment]
Update paper to greek letter spelled out with number in parentheses

**Comment by adm2583** [comment]
This was done by someone else.
