### ISSUE TITLE
Add support for multiple vaccines

### ISSUE THREAD

**Issue by jonahdf** [JoviaNierenberg/COVID-Event-Safety-Modeling#2]
There is no built-in method in Covasim for anything other than a point estimate for vaccine efficacy (symptom and infection). Try to figure out a way to build this ourselves, or just scrap it for simplification purposes.

**Comment by JoviaNierenberg** [comment]
Look into percentages of each vaccine. Look for a more recent study with real world efficacy.

**Comment by adm2583** [comment]
https://covid.cdc.gov/covid-data-tracker/#vaccinations <- COVID vaccines administered by type
I think the overwhelming percentage of Pfizer & Moderna vs J&J vaccines gives support for scrapping this for simplification purposes. We could say that the majority of vaccines in the U.S. are Pfizer & Moderna (95% & 94% respectively) give support for omitting vaccine efficacy in the model. 
https://www.healthline.com/health/vaccinations/pfizer-vaccine-efficacy#efficacy-timeline <- efficacy of different COVID vaccines
