### ISSUE TITLE
Specify demographics of population

### ISSUE THREAD

**Issue by jonahdf** [JoviaNierenberg/COVID-Event-Safety-Modeling#22]
> What does this population look like? What adjustments can be made for tailoring?

**Comment by jonahdf** [comment]
https://docs.idmod.org/projects/covasim/en/latest/tutorials/tut_people.html

Describe hybrid population type, and consider adding some sort of customization

**Comment by jonahdf** [comment]
Added sentence to end of methods.

**Comment by JoviaNierenberg** [comment]
Becomes less relevant since we're using state level populations. Need to add a description of the state level data instead.

**Comment by JoviaNierenberg** [comment]
Put placeholder sentence in paper, citing the COVASIM paper, on how COVASIM handles state level data.

**Comment by JoviaNierenberg** [comment]
Added sentence to methods "All model runs will require the user to specify a US state or to use the general United States population, using Covasim’s included population data from publicly available sources."
