### ISSUE TITLE
Calculate infections at state level

### ISSUE THREAD

**Issue by JoviaNierenberg** [JoviaNierenberg/COVID-Event-Safety-Modeling#23]
Infections or cases? If the former, describe the estimation process (what are the assumptions inherent to it?)

**Comment by JoviaNierenberg** [comment]
Describe resource or replace it

**Comment by JoviaNierenberg** [comment]
Added description of modeling used to estimate infections: 

The CDC estimated 83.1 million total infections, as of January 15, 202118 using a probabilistic multiplier model based on laboratory confirmed case counts, testing practices, and assay sensitivity.19

**Comment by jonahdf** [comment]
Consider doing more up-to-date estimate of natural immunity (30-33%)?

**Comment by JoviaNierenberg** [comment]
Use state level

**Comment by JoviaNierenberg** [comment]
This is done?

**Comment by s67sea** [comment]
Not on the currently live version
