### ISSUE TITLE
Test specificity

### ISSUE THREAD

**Issue by JoviaNierenberg** [JoviaNierenberg/COVID-Event-Safety-Modeling#28]
This needs clarification; do we mean individuals who test positive by rapid antigen test will be assigned a beta multiplier of .98 to reflect that there's a ~2% false positive rate (as per ~95% specificity)?

If so, how are we taking into account the poor sensitivity of the test?

**Comment by JoviaNierenberg** [comment]
Update based on more recent paper if there is one

**Comment by adm2583** [comment]
Is there separation between symptomatic and asymptomatic tests? https://www.cdc.gov/mmwr/volumes/69/wr/mm695152a3.htm
Guessing no but worth considering

**Comment by JoviaNierenberg** [comment]
Updated language to "A recent CDC MMWR report found that antigen tests had a sensitivity of 41.2% and a specificity of 98.4% among asymptomatic university students.38 Subsequently, we will model rapid antigen tests as a multiplier of beta by 0.98, to capture the proportion of total negative tests that are true negatives. Anyone with a (true or false) positive test will not be admitted to the event. "
