### ISSUE TITLE
Numbers used in model

### ISSUE THREAD

**Issue by JoviaNierenberg** [JoviaNierenberg/COVID-Event-Safety-Modeling#31]
So, this is RR; previously, we looked at odds; and a little further down, we're looking at probability

I'm not running the numbers on my end, but all of these need to be carefully reasoned out w.r.t. impact on beta in an Appendix; they mean different things, and we want to make sure they're interpreted correctly

**Comment by JoviaNierenberg** [comment]
Double check numbers and assumptions in paper/spreadsheet https://docs.google.com/spreadsheets/d/17sMwfOsSv3EwgEXE7QveMN-lp9KxOxwx1SDSlV-bnvQ/edit#gid=0

**Comment by s67sea** [comment]
https://docs.google.com/document/d/18vm3BvP2tFwlX8lqerXjSYHFhKMP3iQxV79R_YXqwmw/edit

**Comment by JoviaNierenberg** [comment]
Thank you Saahil!
