### ISSUE TITLE
Vaccine symptom reduction

### ISSUE THREAD

**Issue by JoviaNierenberg** [JoviaNierenberg/COVID-Event-Safety-Modeling#38]
Against disease?

**Comment by adm2583** [comment]
CDC has reported 10,262 breakthrough infections in the U.S. among fully vaccinated individuals; 73% of breakthrough infections as symptomatic as of April 30, 2021. 10% were hospitalized and 2% died. 
They do qualify that these numbers are likely underreported. 
Source: https://www.cdc.gov/mmwr/volumes/70/wr/mm7021e3.htm

**Comment by adm2583** [comment]
Double check if CDC is still tracking break through infections.

**Comment by adm2583** [comment]
CDC is not reporting breakthrough infections anymore but focusing on hospitalizations and deaths. https://www.cdc.gov/vaccines/covid-19/health-departments/breakthrough-cases.html

**Comment by JoviaNierenberg** [comment]
Since we are only addressing infections and not infection severity, I am closing this issue.
