### ISSUE TITLE
Add mixed baseline for outdoor/indoor comparison graph

### ISSUE THREAD

**Issue by jonahdf** [JoviaNierenberg/COVID-Event-Safety-Modeling#39]

**Comment by jonahdf** [comment]
Running into a problem where all the lines display, but the legend can't show more than 5 entries.
![image](https://user-images.githubusercontent.com/39545486/115630552-d58f5a00-a2c9-11eb-945a-e87eac7421be.png)

**Comment by jonahdf** [comment]
Just figure out way around (photoshop on new legend), reduce to 5, etc.

**Comment by JoviaNierenberg** [comment]
We are now using one prevalence. Figure added. 
![newplot](https://user-images.githubusercontent.com/12420449/128948395-a32cb646-4c96-44ac-bba8-77698af8f055.png)
![newplot (1)](https://user-images.githubusercontent.com/12420449/128948398-107eb26f-5dff-4ae0-9150-96b308b07a1c.png)
