### ISSUE TITLE
App blurb

### ISSUE THREAD

**Issue by JoviaNierenberg** [JoviaNierenberg/COVID-Event-Safety-Modeling#51]
Write app blurb explaining how to use the app

**Comment by JoviaNierenberg** [comment]
This tool helps you estimate the COVID risk of holding in-person events and find effective safety measures for minimizing transmission. You can compare multiple custom strategies on the same plot. For example, you can compare hosting your event in North Carolina requiring masks to in North Dakota requiring vaccines.

**Comment by JoviaNierenberg** [comment]
Add basic info about some of the interventions (for example, outdoor events are safer than indoor events)

**Comment by JoviaNierenberg** [comment]
Link to our paper and covasim paper

**Comment by JoviaNierenberg** [comment]
This tool helps you estimate the COVID risk of holding in-person events and find effective safety measures for minimizing transmission. Generally, you can make an event safer by requiring vaccination, testing participants, gathering outside, reducing event capacity, increasing ventilation, and/or requiring masks. You can compare multiple custom strategies on the same plot below. For example, you can compare hosting your event in North Carolina requiring masks to in North Dakota requiring vaccines. Our methods can be found at [link] and all models were run using Covasim [link: http://paper.covasim.org].

**Comment by JoviaNierenberg** [comment]
@shagunn just assigned the issue to you to add the blurb to the app. Thanks!

**Comment by s67sea** [comment]
Added!
