### ISSUE TITLE
Update total previous infections based on CDC April update

### ISSUE THREAD

**Issue by JoviaNierenberg** [JoviaNierenberg/COVID-Event-Safety-Modeling#58]
CDC updated their estimates for total number of infected persons, so I updated the paper: "CDC estimated 114.6 million total infections, as of April 14, 202120 using a probabilistic multiplier model based on laboratory confirmed case counts, testing practices, and assay sensitivity based on multiple studies.21 The 2019 US Census estimated the total US population as 328.2 million,22 indicating that considering prior infections, the proportion of the populace still susceptible to the disease is 1-(114.6/328.2) ≅ 65.1%"

**Comment by JoviaNierenberg** [comment]
Is this updated in the app?

**Comment by shagunn** [comment]
Duplicate issue
