### ISSUE TITLE
Prevalence

### ISSUE THREAD

**Issue by JoviaNierenberg** [JoviaNierenberg/COVID-Event-Safety-Modeling#59]
Look into prevalence calculation
https://www.google.com/search?q=prevalence+calculator+covid&oq=prevalence+calculator+covid&aqs=chrome..69i57j0i22i30j0i390l3.6383j0j1&sourceid=chrome&ie=UTF-8

**Comment by JoviaNierenberg** [comment]
We can calculate prevalence as:
sum(cases over last 10 days)*4.3

A meta analysis in Lancet Microbe found that "Duration of infectiousness and subsequent isolation timelines could reflect viral load dynamics and could be counted from symptom onset for 10 days in non-severe cases." https://www.thelancet.com/journals/lanmic/article/PIIS2666-5247(20)30172-5/fulltext
A modeling study in JAMA Network Open also used 10 days as their infectivity period https://jamanetwork.com/journals/jamanetworkopen/fullarticle/2774707/ 

The CDC estimates that 1 in 4.3 infections were reported https://www.cdc.gov/coronavirus/2019-ncov/cases-updates/burden.html

If we want to use state level data to handle underreporting instead of using a multiplier of 4.3 everywhere, we can use the same prevalence ratio as microcovid, which was developed from COVID-19 Projections: 
prevalance_ratio = 1250 / (day_i + 25) * positive_test_rate ** 0.5 + 2
true_infections = prevalance_ratio * reported_infections
where day_i = number of days since 2020-02-12

If we do this, we would need to estimate the true infections for each of the last 10 days then sum them

**Comment by JoviaNierenberg** [comment]
https://www.microcovid.org/paper/all

**Comment by JoviaNierenberg** [comment]
Start with the first method
Compare prevalence estimates for the second option later

**Comment by shagunn** [comment]
Used first method in app
