### ISSUE TITLE
Look for available domain names

### ISSUE THREAD

**Issue by JoviaNierenberg** [JoviaNierenberg/COVID-Event-Safety-Modeling#61]

**Comment by JoviaNierenberg** [comment]
covidsafeevents.net
covideventmodeling.com
covid19eventsafety.com
covideventplan.com
covideventplanning.org
eventsafetycovid.com

**Comment by shagunn** [comment]
covidfreevents.com
covideventplanner.com
covid19eventplanner.com
safecovidevents.com

**Comment by JoviaNierenberg** [comment]
covideventplanner.com purchased!
