### ISSUE TITLE
Update testing infection delay

### ISSUE THREAD

**Issue by JoviaNierenberg** [JoviaNierenberg/COVID-Event-Safety-Modeling#62]

**Comment by JoviaNierenberg** [comment]
Does it make sense to simplify to:
sum[(1/window)*pop*incidence*x]
where x goes from 1 to window

**Comment by JoviaNierenberg** [comment]
Language updated in paper. Close once updated in app.

**Comment by JoviaNierenberg** [comment]
Use average cases for last week

**Comment by shagunn** [comment]
Updated to use average new cases for the last 7 days.
