### ISSUE TITLE
Look for non-intuitive mitigation measures

### ISSUE THREAD

**Issue by jonahdf** [JoviaNierenberg/COVID-Event-Safety-Modeling#7]
Maia's comment: 

> As noted above, I think next steps should involve moving past what could be considered intuitive to see if we can identify any interesting combinatorics of mitigation measures that yield the highest amount of protection (especially in situations where vaccination may not be feasible)

**Comment by jonahdf** [comment]
Play around with combinations of mitigation measures. Keep updating this issue with ideas to test out in the models.

**Comment by JoviaNierenberg** [comment]
Keep in mind as we read through the paper - are there any measures that aren't in the paper? Thinking it through thoroughly could be a later issue though.

**Comment by JoviaNierenberg** [comment]
Look at combinations that are most and least useful

**Comment by s67sea** [comment]
Considering a baseline of mixed event setting, no testing, default vaccination and no mask wearing (and running a 5-day event with 1000 attendees), comparing cumulative infections at the end of the 5th day, 
- moving the event indoors increases cases by 3.19x
- moving the event outdoors decreases cases by 33.6%
- 4-day PCR decreases cases by 83.2% while daily antigen aswell as entry antigen prevents any cases at all
- Mask wearing reduces cases by 26.9%
- Mandatory vaccination decreases cases by 34.5%***

Some things we could put in the paper: testing is the important factor, more than the setting in which the event is held or the requirement for mask wearing.

***Just realised a problem when testing out combinations: the “initial # of cases” is calculated as the same number irrespective of what % of the population is vaccinated. This makes the effectiveness of intervention “mandatory vaccination” seem lower than it actually is.

**Comment by s67sea** [comment]
- Obviously the worst combination would be indoor setting with no testing, vaccination or masking requirements
- The most effective interventions are testing and mandatory vaccination, as they prevent initial cases from occurring. They are far more effective than the interventions that can be put in place once the population arrives to the venue, such as indoor/outdoor or masking

**Comment by s67sea** [comment]
One of the things people I talked to mentioned for another option we could add to the menu is whether or not there is food allowed at the event. Since allowing people to eat (and hence be in close proximity without masks) negates a good portion of the case reduction that is achieved through a mask mandate

**Comment by s67sea** [comment]
A problem when testing out combinations: the “initial # of cases” is calculated as the same number irrespective of what % of the population is vaccinated. This makes the effectiveness of intervention “mandatory vaccination” seem lower than it actually is.

**Comment by JoviaNierenberg** [comment]
Added figure combining interventions
