### ISSUE TITLE
No/low transmission on days 0 and 1

### ISSUE THREAD

**Issue by JoviaNierenberg** [JoviaNierenberg/COVID-Event-Safety-Modeling#72]
Should we show this differently?

**Comment by JoviaNierenberg** [comment]
Start graph at day 1 instead of day 0
For 1 day events, we are interested in the infections that show up on day 2

Try shifting the graph by 1 day so that the infections that occur on day 1 show up on day 1 and the infections that occur on day 2 show up on day 2, etc.

**Comment by s67sea** [comment]
Implemented on local version. Yet to push to live site.

**Comment by s67sea** [comment]
Pushed to live site.
