### ISSUE TITLE
Add graph legend

### ISSUE THREAD

**Issue by JoviaNierenberg** [JoviaNierenberg/COVID-Event-Safety-Modeling#77]
Define estimate and confidence interval.

**Comment by shagunn** [comment]
Added to the app.py file and pushed to GitHub. Both plots currently have a legend as follows:
<img width="595" alt="Screen Shot 2021-08-09 at 1 03 16 PM" src="https://user-images.githubusercontent.com/31971860/128745410-a0c5af7a-f5a1-4862-986e-2a98e07a5f8a.png">

Can update later to have 1 legend below both plots.
