### ISSUE TITLE
Update incidence

### ISSUE THREAD

**Issue by JoviaNierenberg** [JoviaNierenberg/COVID-Event-Safety-Modeling#82]
Need to divide number of cases by population to calculate incidence. Update the incidence calculations in the dash/live version to: 

incidence_avg = mean(can_usa_timeseries.iloc[range(-7,0,1)]['actuals.newCases'].values)/location_pop # avg new cases last 7 days divided by population

incidence_avg = mean(can_state_timeseries[can_state_timeseries['state']==state_abv].iloc[range(-7,0,1)]['actuals.newCases'].values)/location_pop

This fixes the issue with PCR testing. Updates have been made in the testbed in the jovia branch.

**Comment by shagunn** [comment]
Added to the main branch
